name: OpenTofu Plan
description: Generate and show OpenTofu execution plan

inputs:
  working_directory:
    description: Path to the OpenTofu configuration directory
    required: true
  plan_binary_file:
    description: Absolute path for the output binary plan file (used by apply)
    required: true
  plan_text_file:
    description: Absolute path for the output human-readable plan file
    required: true

outputs:
  plan_text_file:
    description: Absolute path to the generated human-readable plan file
    value: ${{ steps.plan.outputs.plan_text_file }}
  plan_binary_file:
    description: Absolute path to the generated binary plan file for apply
    value: ${{ steps.plan.outputs.plan_binary_file }}

runs:
  using: composite
  steps:
    - name: Plan OpenTofu changes
      id: plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-plan.sh \
          "" \
          "${{ inputs.plan_binary_file }}" \
          "${{ inputs.plan_text_file }}"
