name: Ansible Install
description: Install Ansible and ansible-lint

runs:
  using: composite
  steps:
    - name: Install Ansible
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/ansible-install.sh
