name: OpenTofu Plan Comment
description: Post OpenTofu plan output as a PR comment

inputs:
  plan_text_file:
    description: Absolute path to the human-readable plan output file
    required: true
  environment:
    description: Target environment name (e.g. dev, staging, prod)
    required: true
  working_directory:
    description: Path to OpenTofu configuration directory (for display purposes)
    required: true

outputs:
  comment_body:
    description: The generated comment body
    value: ${{ steps.comment.outputs.comment_body }}

runs:
  using: composite
  steps:
    - name: Generate comment body
      id: comment
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-plan-comment.sh \
          ${{ inputs.plan_text_file }} \
          ${{ inputs.environment }} \
          ${{ inputs.working_directory }}

    - name: Find existing comment
      id: find-comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions[bot]
        body-includes: "**Environment:** `${{ inputs.environment }}`"

    - name: Create or update comment
      id: create-comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.comment.outputs.comment_body }}
        edit-mode: replace
